{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-deployment.serviceAccountName" . }}
  labels:
{{ include "base-deployment.labels" . | nindent 4 }}
{{- end -}}
